#! /bin/bash
set -f
tables=("student" "class" "school")
typeset -a query
function insert {
	if [[ $# -ge 3 ]] ; then
		if [[ ${1^^} == "INTO" ]] ; then
			if [[ `grep -w "^"$2"$" DB/school/db.config` ]]; then
				if [[ ${3^^} == "VALUES" || ${3^^} == "VALUE" ]] ; then
					values=${@:4}
					IFS=","
					for value in ${values[@]}
					do	
						if [[ $value ]] ; then
							vals+=(`echo $value | xargs`) # xargs to trim
						fi
					done
					for val in ${vals[@]}
					do	
						echo $val
					done 
				else
					zenity --info --text="wrong syntax"
				fi
			else
				zenity --info --text="table : $2 is not exist"
			fi
		fi
	else
		zenity --info --text="wrong syntax"
		return 0
	fi
}

function SELECT {
	if [[ " ${*^^} " =~ " FROM " ]] ; then
		typeset -a query
		typeset -a cols
		typeset -i numberOfFrom
		typeset -i numberOfWhere
		numberOfWhere=0
		query+=(${@})

		for i in ${!query[@]}
		do
			if [[ ${query[$i]^^} == "FROM" || ${query[$i]^^} == "WHERE" ]] ; then
				break;
			fi
			cols+=(${query[$i]})
		done
		i=0
		for i in ${!query[@]}
		do
			if [[ "${query[$i]^^}" == "FROM" ]] ; then
				numberOfFrom=$i
			fi

			if [[ "${query[$i]^^}" == "WHERE" ]] ; then
				numberOfWhere=$i
			fi
		done
		echo ${cols[0]}
		echo ${cols[1]}
	else
		zenity --info --text="wrong syntax"
	fi
}

function UPDATE {
	# UPDATE table SET changeColumn = newValue WHERE condCol = condValue
	if [[ "${2^^}" == "SET" ]] ; then
		echo "SET oky"
		if [[ "${6^^}" == "WHERE" ]] ; then
			echo "Where oky"
			tableName="$1"
			changeColumn="$3"
			newValue="$5"
			condCol="$7"
			condValue="$9"
			zenity --info --text="We will change $changeColumn to $newValue where $condCol = $condValue in table $tableName"
		else
			zenity --info --text="wrong syntax WHERE"
		fi
		
	else
		zenity --info --text="wrong syntax SET"
	fi
}

while [[ breakQueryLoop != "break" ]]
do
	query=`zenity --entry --text="add query"`
	if [[ $? == 1 ]] ; then
		breakQueryLoop="break"
		break
	fi
	eval 'for word in '$query'; do echo $word; done'
	if [[ $query ]] ; then 
		if [[ ${query[0]^^} == "SELECT" ]] ; then
			SELECT "${query[@]:1}";
		elif [[ ${query[0]^^} == "INSERT" ]] ; then
			insert "${query[@]:1}"
		elif [[ ${query[0]^^} == "DELETE" ]] ; then
			zenity --info --text="function of ${query[0]^^} "
		elif [[ ${query[0]^^} == "UPDATE" ]] ; then
			echo "this is element number 7 : "${query[7]}
			for o in ${query[@]}
			do
				echo $o
			done
			UPDATE "${query[@]:1}";
		elif [[ ${query[0]^^} == "DROP" ]] ; then
			zenity --info --text="function of ${query[0]^^} "
		elif [[ ${query[0]^^} == "CREATE" ]] ; then
			zenity --info --text="function of ${query[0]^^} "
		elif [[ ${query[0]^^} == "USE" ]] ; then
			zenity --info --text="function of ${query[0]^^} "
		else
			zenity --info --text="comand ${query[0]} not found"
		fi
	fi
done
#update class set name = "Muhammed Adel" Where id = 7